CREATE TABLE tags (id BIGINT NOT NULL AUTO_INCREMENT,
					story_id BIGINT NOT NULL,
					tag_name VARCHAR(255) NOT NULL,
					PRIMARY KEY (id)) ENGINE=INNODB;

--//@UNDO

DROP TABLE IF EXISTS tags;