ALTER TABLE stories CHANGE content content VARCHAR(255) NOT NULL;
ALTER TABLE stories CHANGE id id INTEGER NOT NULL AUTO_INCREMENT;
--//@UNDO

ALTER TABLE stories CHANGE content content TEXT NOT NULL;
ALTER TABLE stories CHANGE id id INT NOT NULL AUTO_INCREMENT;
